### ISSUE TITLE
WYSIWYG Editor

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/vue-form-elements#15]
I'd like to enhance the text editor to allow for a more rich environment on the page. To do this I'd like to add a WYSIWG editor to the input box on the side bar. Extra points for allowing editing inline on the main canvas. 

use https://www.tinymce.com/docs/integrations/vue/

**Comment by velkymx** [comment]
![image](https://user-images.githubusercontent.com/535300/52656618-93795b00-2eab-11e9-81b9-03256e0d76e3.png)

Features to expose: font style (h1, pre, etc), bold, italic, align (left, center and right), link and code view

**Comment by velkymx** [comment]
If we have room, show the numbered and unnumbered lists

**Comment by tdondich** [comment]
As long as tinymce can export bootstrap related classes.  Another one that is bootstrap orientated I believe is summernote.  Also a more simplified verison for text could be Trix, https://trix-editor.org/.  This editor is used for Laravel Nova's wysiwyg editor and might be more appropriate.

I only say this because I know integration of tinymce is a huge pain in the butt.

**Comment by velkymx** [comment]
I'd like to also make sure we can bind parts of the html to the data model. 

Use case: a URL generated by a script task

**Comment by velkymx** [comment]
This is interesting too: https://chmln.github.io/vue-wysiwyg/

**Comment by velkymx** [comment]
Also we need to verify that those tags are whitelisted as part of the save process.

**Comment by tdondich** [comment]
Note the mustache syntax is parsed during rendering.  So as long as the mustache syntax is intact in the content, it'll still work.

**Comment by velkymx** [comment]
Duplicate: https://github.com/ProcessMaker/vue-form-builder/issues/62
